import {
  Mail,
  Shirt,
  Book,
  Wrench,
  Cctv,
  Sofa,
  LayoutGrid,
  ChevronDown,
  ChevronRight,
  Trash2,
  LockKeyhole,
  User,
  LogOut,
  List,
  Car,
  Dice5,
  Volleyball,
  Headphones,
  AppWindowMac,
  Camera,
  House,
  CirclePlus,
  UserRoundSearch,
  Landmark,
  Atom,
  Brain,
  CircleDollarSign,
  Kayak,
  Rocket,
  Axe,
} from "lucide-react-native";

const LucideIcons = {
  clothing: Shirt,
  books: Book,
  tools: Wrench,
  electronics: Cctv,
  furniture: Sofa,
  mail: Mail,
  apps: LayoutGrid,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  bin: Trash2,
  lock: LockKeyhole,
  user: User,
  logout: LogOut,
  list: List,
  cars: Car,
  games: Dice5,
  sports: Volleyball,
  movies: Headphones,
  others: AppWindowMac,
  camera: Camera,
  house: House,
  circlePlus: CirclePlus,
  biography: UserRoundSearch,
  history: Landmark,
  science: Atom,
  psychology: Brain,
  economics: CircleDollarSign,
  adventure: Kayak,
  scifi: Rocket,
  crime: Axe,
};

export default LucideIcons;
